//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vnnews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int ad_id { get; set; }
        public string ad_img { get; set; }
        public Nullable<System.DateTime> ad_datecreate { get; set; }
        public Nullable<System.DateTime> ad_dateupdate { get; set; }
        public string ad_note { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> ad_active { get; set; }
        public Nullable<bool> ad_bin { get; set; }
    
        public virtual User User { get; set; }
    }
}
