//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vnnews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactad
    {
        public int contactads_id { get; set; }
        public string contactads_phone { get; set; }
        public string contactads_zalo { get; set; }
        public string contactads_fb { get; set; }
        public string contactads_email { get; set; }
        public string contactads_content { get; set; }
        public Nullable<System.DateTime> contactads_datecreate { get; set; }
        public Nullable<System.DateTime> contactads_dateend { get; set; }
        public string contactads_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> contactads_browser { get; set; }
    
        public virtual User User { get; set; }
    }
}
