//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vnnews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editor
    {
        public int editor_id { get; set; }
        public string editor_fullname { get; set; }
        public Nullable<int> sex_id { get; set; }
        public string editor_fb { get; set; }
        public string editor_phone { get; set; }
        public string editor_time { get; set; }
        public string editor_introduce { get; set; }
        public string editor_interests { get; set; }
        public string editor_enthusiasm { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> editor_datecreate { get; set; }
        public Nullable<System.DateTime> editor_dateupdate { get; set; }
        public Nullable<bool> editor_browser { get; set; }
    
        public virtual Sex Sex { get; set; }
        public virtual User User { get; set; }
    }
}
