//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vnnews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int report_id { get; set; }
        public string report_content { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> news_id { get; set; }
        public Nullable<System.DateTime> report_datecreate { get; set; }
        public Nullable<int> dow_id { get; set; }
    
        public virtual Dow_id Dow_id1 { get; set; }
        public virtual News News { get; set; }
        public virtual User User { get; set; }
    }
}
